language: node_js
node_js:
  - 14
install:
  - npm install
script:
  - echo "skipping tests"
deploy:
  provider: s3
  access_key_id: "AKIAVCO44IP6FXIR5TIZ"
  secret_access_key: $KEYTHING
  bucket: "foinse.io"
  skip_cleanup: true
  local_dir: build
  upload_dir: resume